/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppSpinner: typeof import('./src/components/AppSpinner.vue')['default']
    CountryItem: typeof import('./src/components/CountryItem.vue')['default']
    CountryList: typeof import('./src/components/CountryList.vue')['default']
    FilterFeild: typeof import('./src/components/FilterFeild.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFeild: typeof import('./src/components/SearchFeild.vue')['default']
  }
}
